import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import BasePageLayout from "@/src/components/Layout/BasePageLayout";


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div>
        <BasePageLayout />
      </div>
    </>
  );
}
